name: Docker-CICD
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      # - name: Login to Tencent Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ secrets.TENCENT_REGISTRY }}
      #     username: ${{ secrets.TENCENT_DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.TENCENT_DOCKERHUB_PASSWORD }}
      - name: Build web docker image
        run: |
          docker build \
          -t sensor-web:latest .
      # - name: Push docker image 
      #   run: |
      #     docker push ${{ secrets.TENCENT_REGISTRY }}/helix/helix-server:latest
      #     docker push ${{ secrets.TENCENT_REGISTRY }}/helix/helix-web:latest
